# WORKSPACE file (top level)
workspace(name = "irc_client")

# BUILD.bazel (in root directory)
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_library(
    name = "logger",
    srcs = ["Logger.cpp"],
    hdrs = ["Logger.hpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "arg_parser",
    srcs = ["ArgParser.cpp"],
    hdrs = ["ArgParser.hpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "ncurses_ui",
    srcs = ["NcursesUI.cpp"],
    hdrs = ["NcursesUI.hpp"],
    copts = ["-std=c++20"],
    deps = [],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "unix_socket_ui",
    srcs = ["UnixSocketUI.cpp"],
    hdrs = ["UnixSocketUI.hpp"],
    copts = ["-std=c++20"],
    deps = [],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "irc_client_lib",
    srcs = ["IRCClient.cpp"],
    hdrs = ["IRCClient.hpp", "IOAdapter.hpp"],
    deps = [
        ":logger",
        ":ncurses_ui",
        ":unix_socket_ui",
    ],
    copts = ["-std=c++20"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "irc-client",
    srcs = ["main.cpp"],
    deps = [
        ":irc_client_lib",
        ":logger",
        ":arg_parser",
        ":ncurses_ui",
        ":unix_socket_ui",
    ],
    copts = ["-std=c++20", "-Wall", "-Wextra"],
    linkopts = ["-lncurses", "-lpthread"],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "arg_parser_test",
    srcs = ["ArgParser_test.cpp"],
    deps = [":arg_parser"],
    copts = ["-std=c++20"],
)
